# Site settings
title: Anastasiia's Portfolio
description: A blog about my projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anastasiia Tychkova
user_description: Front-end Developer with experience building responsive websites and specializing in HTML5, SCSS, Vanilla JavaScript and frameworks Vue.js and React. I am a Junior Front-End Developer with 1 year experience of building eye-catching responsive websites.
  I really enjoy working both independently and within a team to deliver a quality product. Moreover, I keen on minimalistic and
  elegant design solutions for users - it satisfies me to see that there is a room for all elements on the website, and they're not crowded.
  I am currently actively using React in my pet projects.
user_title: Front-End Developer
email: tychkovaam@gmail.com
github_username:  tychtych
gplus_username:  tychkovaam

# Google-analytics
google-analytics:
  id: "UA-38520953-3"

exclude: ['package.json', 'src' , 'node_modules']
