# Site settings
title: Anastasiia's Portfolio
description: A blog about my projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anastasiia Tychkova
user_description: Front-end Specialization Course fresh grad with experience building responsive websites and specializing in HTML5, SCSS, and Vanilla JavaScript with project experience working with Vue.js and Nuxt.js. Using React for pet projects.
user_title: Front-End Developer
email: tychkovaam@gmail.com
github_username:  tychtych
gplus_username:  tychkovaam

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
